server:
  port: 80

spring:
  application:
    name: microcloud-consumer-product-feign
  zipkin:
    base-url: http://localhost:8501 #所有数据提交到此服务中
  sleuth:
    sampler:
      percentage: 1.0 #定义抽样比例 默认为0.1

eureka:
  client:
    service-url:
      #defaultZone: http://eureka:eureka@eureka-7001.com:7001/eureka/,http://eureka:eureka@eureka-7002.com:7002/eureka/,http://eureka:eureka@eureka-7003.com:7003/eureka/
      defaultZone: http://eureka:eureka@eureka-7004.com:7004/eureka/
  instance:
    #在信息列表中显示主机名称
    instance-id: www.lxc.com
    #访问的路径变成ip地址
    prefer-ip-address: true

feign:
  compression:
    request:
      mime-types: #配置接口能够压缩式类型
          - text/xml
          - application/xml
          - application/json
      min-request-size: 2048 #超过2048的请求都会被压缩
#配置日志等级 查看feign 接口服务调用的整个过程
logging:
  level:
    com.liuxc.www.microcloud.service: debug
ribbon:
  eureka:
    enabled: true
