#tomcat信息配置
server:
  port: 7002

#spring 信息配置
spring:
  application:
    name: eureKa-server-7002

#注册中心配置
eureka:
  instance:                           #eureka 实例
    hostname: eureKa-7002.com         #eureka 主机名
  client:                             #在默认设置下，Eureka服务注册中心也会将自己作为客户端来尝试注册它自己
    register-with-eureka: false       #所以我们需要禁用它的客户端注册行为。
    fetch-registry: false
    service-url:
      defaultZone: http://eureka:eureka@eureka-7001.com:7001/eureka/,http://eureka:eureka@eureka-7003.com:7003/eureka/
  server:
    eviction-interval-timer-in-ms: 60000 #设置清理的间隔时间，默认是60*1000； 60秒

#安全认证配置
security:
  basic:
    #开启安全认证
    enabled: true
  user:
    name: eureka
    password: eureka
    role: USER
