server:
  port: 7201

spring:
  application:
    name: microcloud-config-bus-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:liuxc1/microcloudconfig.git #设置GIT厂库的连接地址
          search-paths: #采用单厂库多目录的方式获取配置文件信息
            - microcloud-*
  rabbitmq: #集成RabbitMQ作为消息服务总线处理
    host: 192.168.20.85
    port: 5672
    virtual-host: /my-virtual-hosts
    username: java
    password: java


eureka:
  client:
    service-url:
      defaultZone: http://eureka:eureka@eureka-7004.com:7004/eureka/
  instance:
    #在信息列表中显示主机名称
    instance-id: www.lxc.com
    #访问的路径变成ip地址
    prefer-ip-address: true
