server:
  port: 80

spring:
  application:
    name: microcloud-consumer-product-feign

eureka:
  client:
    service-url:
      #defaultZone: http://eureka:eureka@eureka-7001.com:7001/eureka/,http://eureka:eureka@eureka-7002.com:7002/eureka/,http://eureka:eureka@eureka-7003.com:7003/eureka/
      defaultZone: http://eureka:eureka@eureka-7004.com:7004/eureka/
  instance:
    #在信息列表中显示主机名称
    instance-id: www.lxc.com
    #访问的路径变成ip地址
    prefer-ip-address: true

feign:
  compression:
    request:
      mime-types: #配置接口能够压缩式类型
          - text/xml
          - application/xml
          - application/json
      min-request-size: 2048 #超过2048的请求都会被压缩
  hystrix:
    enabled: true #开启熔断机制

#配置日志等级 查看feign 接口服务调用的整个过程
logging:
  level:
    com.liuxc.www.microcloud.service: debug

## hystrix相关配置
## hystrix默认会读取classpath下的config.properties文件，application会覆盖config.properties中的属性
hystrix:
  command:
    #指定服务配置
    MICROCLOUD-PROVIDER-PRODUCT:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
      # 指定feign客户端中具体的方法
    #IProductService#getList():
        #execution:
          #isolation:
            #thread:
             # timeoutInMilliseconds: 2000
    # 这是默认的配置 default全局有效，service id指定应用有效
    default:
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为熔断根据
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 3000

 #这些配置是基于Archaius的，我们可以看DefaultClientConfigImpl这个类
ribbon:
  eureka:
    enabled: true
  # 配置ribbon默认的超时时间
  ConnectTimeout: 2000  # 默认会读取classpath下的config.properties文件，application会覆盖config.properties中的属性
  ReadTimeout: 3000

